chore: fix indentation on Game and Root
dbyington/tworooms pull request #13
Opened 2017-08-08 13:33 UTC by jmporchet

2017-08-08 13:50 UTC, arol requested changes

2017-08-08 13:50 UTC, arol commented on imports/ui/Game.jsx
> +import SwipeableViews from "react-swipeable-views";
JS! use single quotes

2017-08-08 16:20 UTC, jmporchet commented
Aaand this is why you should not rely blindly on plugins to do your dirty work...

2017-08-08 18:37 UTC, arol requested changes

2017-08-08 18:37 UTC, arol commented on imports/ui/Game.jsx
>      if (this.props.game.running) {
remove this if statement (it's doing nothing)

2017-08-08 18:37 UTC, arol commented on imports/ui/Game.jsx
> +            onTouchTap={() => this.nextRound()}
Just FYI, here, you're creating a new function on every `render` call and it's inefficient. You should pass it as `onTouchTap={this.nextRound}` and declaring the function as `nextRound = () => {…}`.

2017-08-08 19:07 UTC, arol submitted a review, later dismissed

2017-08-09 13:25 UTC, dbyington approved these changes
I approve this pull request

2017-08-09 13:26 UTC, merged